name: Build TWRP A11-12.1

on:
  workflow_dispatch:
    inputs:
      MANIFEST_TYPE:
        description: 'MANIFEST_TYPE'
        required: true
        default: 'twrp'
        type: choice
        options:
        - twrp
        - omni
      MANIFEST_URL:
        description: 'MANIFEST_URL'
        required: true
        default: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git'
      LIBRARY_BRANCH:
        description: 'LIBRARY_BRANCH'
        required: true
        default: 'twrp-12.1'
        type: choice
        options:
        - twrp-11
        - twrp-12.1
      DEVICE_TREE_URL:
        description: 'DEVICE_TREE_URL'
        required: true
        default: 'https://github.com/brigudav/android_device_xiaomi_surya_twrp.git'
      DEVICE_TREE_BRANCH:
        description: 'DEVICE_TREE_BRANCH'
        required: true
        default: 'android-12.1'
      DEVICE_PATH:
        description: 'DEVICE_PATH'
        required: true
        default: 'device/xiaomi/surya'
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: true
        default: 'surya'
      DEVICE_TYPE:
        description: 'DEVICE_TYPE'
        required: true
        default: 'recovery'
        type: choice
        options:
        - recovery
        - boot
        - vendorboot
      UPLOAD:
        description: 'Upload to Telegram Bot (true or false)'
        required: true
        default: 'yes'
        type: choice
        options:
        - yes
        - no
      PUBLISH:
        description: 'Publish to GitHub (true or false)'
        required: true
        default: 'yes'
        type: choice
        options:
        - yes
        - no

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-18.04

    steps:
    - name: Remove Useless Package
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
        sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo apt -y autoremove --purge
        sudo apt -y autoclean
        sudo apt clean

    - name: Maximize Build Space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 1024
        swap-size-mb: 10240
        remove-dotnet: 'true'
        temp-reserve-mb: 1024
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Check Out Repository
      uses: actions/checkout@v3

    - name: Prepare Environment
      run: |
        export HOME=${GITHUB_WORKSPACE}
        cd ${GITHUB_WORKSPACE}
        sudo apt -y install git aria2 
        git clone https://github.com/brigudav/scripts
        cd scripts
        sudo bash setup/android_build_env.sh
        sudo bash setup/install_android_sdk.sh || true

    - name: Init Repo
      run: |
        mkdir ${GITHUB_WORKSPACE}/workspace
        cd ${GITHUB_WORKSPACE}/workspace
        git config --global user.name "brigudav"
        git config --global user.email "alexvl1972@hotmail.com"
        repo init --depth=1 -u ${{ github.event.inputs.MANIFEST_URL }} -b ${{ github.event.inputs.LIBRARY_BRANCH }}

    - name: Repo Sync
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Repopick Fscrypt
      if: ${{ github.event.inputs.MANIFEST_URL == 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git' && github.event.inputs.LIBRARY_BRANCH == 'twrp-12.1' }}
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        source build/envsetup.sh
        repopick 5405
        repopick 5540

    - name: Clone Device Tree
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}

    - name: Building recovery
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch ${{ github.event.inputs.MANIFEST_TYPE }}_${{ github.event.inputs.DEVICE_NAME }}-eng
        make clean
        make ${{ github.event.inputs.DEVICE_TYPE }}image -j$(nproc --all)

    - name: Set Variables
      run: |
        echo "::set-output name=date::$(TZ=Australia/Sydney date +%Y%m%d-%H%M)"
        echo "::set-output name=Outdir::${GITHUB_WORKSPACE}/workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}"
      id: var

    - name: Add Img to Zip
      run: |
        cd ${{ steps.var.outputs.Outdir }}
        zip -9 twrp-${{ github.event.inputs.DEVICE_NAME }}-${{ steps.var.outputs.date }}.zip ${{ github.event.inputs.DEVICE_TYPE }}.img
        echo "::set-output name=name::$(find * -name *.zip -type f)"
      id: zipname

    - name: Upload to Telegram Bot
      if: github.event.inputs.UPLOAD == 'true'
      env:
        CHAT_ID: ${{ secrets.TELEGRAM_TO }}
        BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      run: |
        export ZIP=${{ steps.var.outputs.Outdir }}/${{ steps.zipname.outputs.name }}
        export CAPTION=\
        *- Device:* ${{ github.event.inputs.DEVICE_NAME }}'\n'\
        *- Time:* $(TZ=Australia/Sydney date +"%Y-%m-%d"-%H:%M:%S)'\n'\
        *- Actor:* ${{ github.actor }}'\n'\
        *- Build:* Test A-12
        curl -F document=@ZIP -F "caption=${CAPTION}" "https://api.telegram.org/bot${BOT_TOKEN}/sendDocument?chat_id=${CHAT_ID}&parse_mode=Markdown"

    - name: Publish to GitHub
      if: github.event.inputs.PUBLISH == 'true'
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.var.outputs.Outdir }}/${{ steps.zipname.outputs.name }}
        name: ${{ steps.zipname.outputs.name }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: Recovery for ${{ github.event.inputs.DEVICE_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.TEST }}
